export const GET_RIDE_DETAILS = 'GET_RIDE_DETAILS';

// Culture
export const CREATE_CULTURE = 'CREATE_CULTURE';
export const GET_CULTURE = 'GET_CULTURE';
export const GET_CULTURE_DETAILS = 'GET_CULTURE_DETAILS';
export const UPDATE_CULTURE = 'UPDATE_CULTURE';
export const DELETE_CULTURE = 'DELETE_CULTURE';
export const SET_CULTURE = 'SET_CULTURE';
export const SET_NEW_CULTURE = 'SET_NEW_CULTURE';
export const DELETE_CULTURE_ITEM = 'DELETE_CULTURE_ITEM';
export const UPDATE_CULTURE_DETAILS = 'UPDATE_CULTURE_DETAILS';
export const SET_CULTURE_DETAILS = 'SET_CULTURE_DETAILS';
export const CLEAR_CULTURE_ITEM = 'CLEAR_CULTURE_ITEM';
