version: "3.4"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: alltopdf
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3305:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 6070:8080

  test:
    depends_on:
      - db
    restart: always
    build:
      ./src
    volumes:
      - ./src:/var/www/html
    ports:
      - 3131:80
